[options]
db_host = db
db_port = 5432
dbfilter = .*
db_name = postgres
db_user = odoo
db_password = odoo
admin_passwd = admin-b
data_dir = /var/lib/odoo
addons_path = /mnt/extra-addons,/mnt/entreprise-addons
